# Generated by Django 5.0.7 on 2024-10-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='weather',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
